-- migrate:up
CREATE TABLE products_info(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  products_id INT NOT NULL,
  stock INT NOT NULL,
  sales INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (products_id) REFERENCES products (id) ON DELETE CASCADE
);

-- migrate:down
DROP TABLE products_info;
