-- migrate:up
CREATE TABLE products_information(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  stock INT NOT NULL DEFAULT 500,
  sales INT NOT NULL DEFAULT 100,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE products_information;
